version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    env_file:
      - ./config/.env
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80"
      environment:
        PMA_HOST: db
      depends_on:
        - db

  xperiment2:
    image: xperiment2_app:latest
    container_name: xperiment2_app
    depends_on:
      - db
    volumes:

      - media_volume:/xperiment2/media
    env_file:
      - ./config/.env
    command: >
      bash -c "gunicorn -b 0.0.0.0:8000 Xperiment2.wsgi:application"
      

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    image: nginx
    container_name: nginx
    volumes:

      - media_volume:/xperiment2/media
    ports:
      - "80:80"
    depends_on:
      - xperiment2

volumes:
  mysql_data:

  media_volume: