# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_set_window_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server_settings(object):
    def setupUi(self, server_settings):
        server_settings.setObjectName("server_settings")
        server_settings.setWindowModality(QtCore.Qt.ApplicationModal)
        server_settings.resize(380, 327)
        server_settings.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(server_settings)
        self.buttonBox.setGeometry(QtCore.QRect(30, 286, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label_serverAddress = QtWidgets.QLabel(server_settings)
        self.label_serverAddress.setGeometry(QtCore.QRect(10, 10, 111, 17))
        self.label_serverAddress.setObjectName("label_serverAddress")
        self.lineEdit_serverAddress = QtWidgets.QLineEdit(server_settings)
        self.lineEdit_serverAddress.setGeometry(QtCore.QRect(10, 32, 361, 25))
        self.lineEdit_serverAddress.setClearButtonEnabled(True)
        self.lineEdit_serverAddress.setObjectName("lineEdit_serverAddress")
        self.spinBox_statusRequestInterval = QtWidgets.QSpinBox(server_settings)
        self.spinBox_statusRequestInterval.setGeometry(QtCore.QRect(10, 85, 65, 26))
        self.spinBox_statusRequestInterval.setMaximum(9999)
        self.spinBox_statusRequestInterval.setProperty("value", 2)
        self.spinBox_statusRequestInterval.setObjectName("spinBox_statusRequestInterval")
        self.label_statusRequestFrequency_1 = QtWidgets.QLabel(server_settings)
        self.label_statusRequestFrequency_1.setGeometry(QtCore.QRect(10, 63, 371, 17))
        self.label_statusRequestFrequency_1.setObjectName("label_statusRequestFrequency_1")
        self.label_parsRequestFrequency_1 = QtWidgets.QLabel(server_settings)
        self.label_parsRequestFrequency_1.setGeometry(QtCore.QRect(10, 117, 351, 17))
        self.label_parsRequestFrequency_1.setObjectName("label_parsRequestFrequency_1")
        self.spinBox_parsRequestInterval = QtWidgets.QSpinBox(server_settings)
        self.spinBox_parsRequestInterval.setGeometry(QtCore.QRect(10, 139, 65, 26))
        self.spinBox_parsRequestInterval.setMaximum(9999)
        self.spinBox_parsRequestInterval.setProperty("value", 2)
        self.spinBox_parsRequestInterval.setObjectName("spinBox_parsRequestInterval")
        self.label_statusRequestFrequency_2 = QtWidgets.QLabel(server_settings)
        self.label_statusRequestFrequency_2.setGeometry(QtCore.QRect(80, 89, 31, 17))
        self.label_statusRequestFrequency_2.setObjectName("label_statusRequestFrequency_2")
        self.label_parsRequestFrequency_2 = QtWidgets.QLabel(server_settings)
        self.label_parsRequestFrequency_2.setGeometry(QtCore.QRect(80, 143, 31, 17))
        self.label_parsRequestFrequency_2.setObjectName("label_parsRequestFrequency_2")
        self.spinBox_statusResponseTimeout = QtWidgets.QSpinBox(server_settings)
        self.spinBox_statusResponseTimeout.setGeometry(QtCore.QRect(10, 192, 65, 26))
        self.spinBox_statusResponseTimeout.setMaximum(9999)
        self.spinBox_statusResponseTimeout.setProperty("value", 10)
        self.spinBox_statusResponseTimeout.setObjectName("spinBox_statusResponseTimeout")
        self.label_statusResponseTimeout_2 = QtWidgets.QLabel(server_settings)
        self.label_statusResponseTimeout_2.setGeometry(QtCore.QRect(80, 196, 31, 17))
        self.label_statusResponseTimeout_2.setObjectName("label_statusResponseTimeout_2")
        self.label_statusResponseTimeout_1 = QtWidgets.QLabel(server_settings)
        self.label_statusResponseTimeout_1.setGeometry(QtCore.QRect(10, 170, 241, 17))
        self.label_statusResponseTimeout_1.setObjectName("label_statusResponseTimeout_1")
        self.label_parsResponseTimeout_2 = QtWidgets.QLabel(server_settings)
        self.label_parsResponseTimeout_2.setGeometry(QtCore.QRect(82, 249, 31, 17))
        self.label_parsResponseTimeout_2.setObjectName("label_parsResponseTimeout_2")
        self.label_parsResponseTimeout_1 = QtWidgets.QLabel(server_settings)
        self.label_parsResponseTimeout_1.setGeometry(QtCore.QRect(12, 223, 351, 17))
        self.label_parsResponseTimeout_1.setObjectName("label_parsResponseTimeout_1")
        self.spinBox_parsResponseTimeout = QtWidgets.QSpinBox(server_settings)
        self.spinBox_parsResponseTimeout.setGeometry(QtCore.QRect(12, 245, 65, 26))
        self.spinBox_parsResponseTimeout.setMaximum(9999)
        self.spinBox_parsResponseTimeout.setProperty("value", 90)
        self.spinBox_parsResponseTimeout.setObjectName("spinBox_parsResponseTimeout")

        self.retranslateUi(server_settings)
        self.buttonBox.accepted.connect(server_settings.accept) # type: ignore
        self.buttonBox.rejected.connect(server_settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(server_settings)

    def retranslateUi(self, server_settings):
        _translate = QtCore.QCoreApplication.translate
        server_settings.setWindowTitle(_translate("server_settings", "Настройки подключения к серверу"))
        self.label_serverAddress.setText(_translate("server_settings", "Адрес сервера:"))
        self.lineEdit_serverAddress.setText(_translate("server_settings", "http://127.0.0.1:8000/api/v1/start/"))
        self.label_statusRequestFrequency_1.setText(_translate("server_settings", "Между запросами статуса сервера"))
        self.label_parsRequestFrequency_1.setText(_translate("server_settings", "Между запусками процессов парсинга, не менее"))
        self.label_statusRequestFrequency_2.setText(_translate("server_settings", "сек"))
        self.label_parsRequestFrequency_2.setText(_translate("server_settings", "сек"))
        self.label_statusResponseTimeout_2.setText(_translate("server_settings", "сек"))
        self.label_statusResponseTimeout_1.setText(_translate("server_settings", "Время ожидания  статуса сервера"))
        self.label_parsResponseTimeout_2.setText(_translate("server_settings", "сек"))
        self.label_parsResponseTimeout_1.setText(_translate("server_settings", "Время ожидания  результатов парсинга, не более"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    server_settings = QtWidgets.QDialog()
    ui = Ui_server_settings()
    ui.setupUi(server_settings)
    server_settings.show()
    sys.exit(app.exec_())
