# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bets_checking_window_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bets_checking(object):
    def setupUi(self, bets_checking):
        bets_checking.setObjectName("bets_checking")
        bets_checking.setWindowModality(QtCore.Qt.ApplicationModal)
        bets_checking.resize(493, 121)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(bets_checking.sizePolicy().hasHeightForWidth())
        bets_checking.setSizePolicy(sizePolicy)
        bets_checking.setMaximumSize(QtCore.QSize(493, 200))
        bets_checking.setModal(True)
        self.frame = QtWidgets.QFrame(bets_checking)
        self.frame.setGeometry(QtCore.QRect(5, 5, 480, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.label_waitBetsResult = QtWidgets.QLabel(self.frame)
        self.label_waitBetsResult.setGeometry(QtCore.QRect(30, 10, 431, 61))
        self.label_waitBetsResult.setObjectName("label_waitBetsResult")
        self.pushButton_skipBetsCheking = QtWidgets.QPushButton(self.frame)
        self.pushButton_skipBetsCheking.setGeometry(QtCore.QRect(168, 78, 141, 23))
        self.pushButton_skipBetsCheking.setObjectName("pushButton_skipBetsCheking")

        self.retranslateUi(bets_checking)
        QtCore.QMetaObject.connectSlotsByName(bets_checking)

    def retranslateUi(self, bets_checking):
        _translate = QtCore.QCoreApplication.translate
        bets_checking.setWindowTitle(_translate("bets_checking", "Поиск сделанных ставок"))
        self.label_waitBetsResult.setText(_translate("bets_checking", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">В реестре обнаружены данные ранее сделанных ставок. <br/>Производится получение результатов для записи <br/>в файл статистики, ожидайте...</span></p></body></html>"))
        self.pushButton_skipBetsCheking.setText(_translate("bets_checking", "Пропустить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bets_checking = QtWidgets.QDialog()
    ui = Ui_bets_checking()
    ui.setupUi(bets_checking)
    bets_checking.show()
    sys.exit(app.exec_())
