# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telegram_settings_window_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telegram_settings(object):
    def setupUi(self, telegram_settings):
        telegram_settings.setObjectName("telegram_settings")
        telegram_settings.setWindowModality(QtCore.Qt.ApplicationModal)
        telegram_settings.resize(493, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(telegram_settings.sizePolicy().hasHeightForWidth())
        telegram_settings.setSizePolicy(sizePolicy)
        telegram_settings.setMinimumSize(QtCore.QSize(493, 200))
        telegram_settings.setMaximumSize(QtCore.QSize(493, 200))
        telegram_settings.setModal(True)
        self.frame = QtWidgets.QFrame(telegram_settings)
        self.frame.setGeometry(QtCore.QRect(5, 5, 480, 190))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 13, 421, 166))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_telegramSettings = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_telegramSettings.setFont(font)
        self.label_telegramSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_telegramSettings.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_telegramSettings.setObjectName("label_telegramSettings")
        self.verticalLayout.addWidget(self.label_telegramSettings)
        self.label_telegramGroupId = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_telegramGroupId.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_telegramGroupId.setAlignment(QtCore.Qt.AlignCenter)
        self.label_telegramGroupId.setObjectName("label_telegramGroupId")
        self.verticalLayout.addWidget(self.label_telegramGroupId)
        self.lineEdit_telegramGroupId = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_telegramGroupId.setText("")
        self.lineEdit_telegramGroupId.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_telegramGroupId.setObjectName("lineEdit_telegramGroupId")
        self.verticalLayout.addWidget(self.lineEdit_telegramGroupId)
        self.label_telegramBotToken = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_telegramBotToken.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_telegramBotToken.setAlignment(QtCore.Qt.AlignCenter)
        self.label_telegramBotToken.setObjectName("label_telegramBotToken")
        self.verticalLayout.addWidget(self.label_telegramBotToken)
        self.lineEdit_telegramBotToken = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_telegramBotToken.setText("")
        self.lineEdit_telegramBotToken.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_telegramBotToken.setObjectName("lineEdit_telegramBotToken")
        self.verticalLayout.addWidget(self.lineEdit_telegramBotToken)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(telegram_settings)
        self.buttonBox.accepted.connect(telegram_settings.accept) # type: ignore
        self.buttonBox.rejected.connect(telegram_settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(telegram_settings)

    def retranslateUi(self, telegram_settings):
        _translate = QtCore.QCoreApplication.translate
        telegram_settings.setWindowTitle(_translate("telegram_settings", "Настройки взаимодействия с Telegram"))
        self.label_telegramSettings.setText(_translate("telegram_settings", "Настройки телеграм-бота"))
        self.label_telegramGroupId.setText(_translate("telegram_settings", "<html><head/><body><p>ID (ссылка-приглашение) группы</p></body></html>"))
        self.lineEdit_telegramGroupId.setPlaceholderText(_translate("telegram_settings", "ID"))
        self.label_telegramBotToken.setText(_translate("telegram_settings", "<html><head/><body><p>Токен бота</p></body></html>"))
        self.lineEdit_telegramBotToken.setPlaceholderText(_translate("telegram_settings", "token"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telegram_settings = QtWidgets.QDialog()
    ui = Ui_telegram_settings()
    ui.setupUi(telegram_settings)
    telegram_settings.show()
    sys.exit(app.exec_())
