# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_set_window_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_servers_settings(object):
    def setupUi(self, servers_settings):
        servers_settings.setObjectName("servers_settings")
        servers_settings.setWindowModality(QtCore.Qt.ApplicationModal)
        servers_settings.resize(380, 269)
        servers_settings.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(servers_settings)
        self.buttonBox.setGeometry(QtCore.QRect(30, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label_serverAddress = QtWidgets.QLabel(servers_settings)
        self.label_serverAddress.setGeometry(QtCore.QRect(10, 10, 111, 17))
        self.label_serverAddress.setObjectName("label_serverAddress")
        self.lineEdit_serverAddress = QtWidgets.QLineEdit(servers_settings)
        self.lineEdit_serverAddress.setGeometry(QtCore.QRect(10, 32, 361, 25))
        self.lineEdit_serverAddress.setClearButtonEnabled(True)
        self.lineEdit_serverAddress.setObjectName("lineEdit_serverAddress")
        self.doubleSpinBox_statusRequestFrequency = QtWidgets.QDoubleSpinBox(servers_settings)
        self.doubleSpinBox_statusRequestFrequency.setGeometry(QtCore.QRect(10, 85, 65, 26))
        self.doubleSpinBox_statusRequestFrequency.setDecimals(1)
        self.doubleSpinBox_statusRequestFrequency.setMaximum(9999.0)
        self.doubleSpinBox_statusRequestFrequency.setSingleStep(0.5)
        self.doubleSpinBox_statusRequestFrequency.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_statusRequestFrequency.setProperty("value", 2.0)
        self.doubleSpinBox_statusRequestFrequency.setObjectName("doubleSpinBox_statusRequestFrequency")
        self.label_statusRequestFrequency_1 = QtWidgets.QLabel(servers_settings)
        self.label_statusRequestFrequency_1.setGeometry(QtCore.QRect(10, 63, 371, 17))
        self.label_statusRequestFrequency_1.setObjectName("label_statusRequestFrequency_1")
        self.label_parsRequestFrequency_1 = QtWidgets.QLabel(servers_settings)
        self.label_parsRequestFrequency_1.setGeometry(QtCore.QRect(10, 117, 351, 17))
        self.label_parsRequestFrequency_1.setObjectName("label_parsRequestFrequency_1")
        self.doubleSpinBox_parsRequestFrequency = QtWidgets.QDoubleSpinBox(servers_settings)
        self.doubleSpinBox_parsRequestFrequency.setGeometry(QtCore.QRect(10, 139, 65, 26))
        self.doubleSpinBox_parsRequestFrequency.setDecimals(1)
        self.doubleSpinBox_parsRequestFrequency.setMaximum(9999.0)
        self.doubleSpinBox_parsRequestFrequency.setSingleStep(0.5)
        self.doubleSpinBox_parsRequestFrequency.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_parsRequestFrequency.setProperty("value", 1.5)
        self.doubleSpinBox_parsRequestFrequency.setObjectName("doubleSpinBox_parsRequestFrequency")
        self.label_statusRequestFrequency_2 = QtWidgets.QLabel(servers_settings)
        self.label_statusRequestFrequency_2.setGeometry(QtCore.QRect(80, 89, 31, 17))
        self.label_statusRequestFrequency_2.setObjectName("label_statusRequestFrequency_2")
        self.label_parsRequestFrequency_2 = QtWidgets.QLabel(servers_settings)
        self.label_parsRequestFrequency_2.setGeometry(QtCore.QRect(80, 143, 31, 17))
        self.label_parsRequestFrequency_2.setObjectName("label_parsRequestFrequency_2")
        self.doubleSpinBox_responseTimeout = QtWidgets.QDoubleSpinBox(servers_settings)
        self.doubleSpinBox_responseTimeout.setGeometry(QtCore.QRect(10, 192, 65, 26))
        self.doubleSpinBox_responseTimeout.setDecimals(1)
        self.doubleSpinBox_responseTimeout.setMaximum(9999.0)
        self.doubleSpinBox_responseTimeout.setSingleStep(0.5)
        self.doubleSpinBox_responseTimeout.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_responseTimeout.setProperty("value", 10.0)
        self.doubleSpinBox_responseTimeout.setObjectName("doubleSpinBox_responseTimeout")
        self.label_responseTimeout_2 = QtWidgets.QLabel(servers_settings)
        self.label_responseTimeout_2.setGeometry(QtCore.QRect(80, 196, 31, 17))
        self.label_responseTimeout_2.setObjectName("label_responseTimeout_2")
        self.label_responseTimeout_1 = QtWidgets.QLabel(servers_settings)
        self.label_responseTimeout_1.setGeometry(QtCore.QRect(10, 170, 241, 17))
        self.label_responseTimeout_1.setObjectName("label_responseTimeout_1")

        self.retranslateUi(servers_settings)
        self.buttonBox.accepted.connect(servers_settings.accept) # type: ignore
        self.buttonBox.rejected.connect(servers_settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(servers_settings)

    def retranslateUi(self, servers_settings):
        _translate = QtCore.QCoreApplication.translate
        servers_settings.setWindowTitle(_translate("servers_settings", "Настройки подключения к серверу"))
        self.label_serverAddress.setText(_translate("servers_settings", "Адрес сервера:"))
        self.lineEdit_serverAddress.setText(_translate("servers_settings", "http://127.0.0.1:8000/api/v1/start/"))
        self.label_statusRequestFrequency_1.setText(_translate("servers_settings", "Между запросами статуса сервера"))
        self.label_parsRequestFrequency_1.setText(_translate("servers_settings", "Между запусками процессов парсинга, не менее"))
        self.label_statusRequestFrequency_2.setText(_translate("servers_settings", "сек"))
        self.label_parsRequestFrequency_2.setText(_translate("servers_settings", "сек"))
        self.label_responseTimeout_2.setText(_translate("servers_settings", "сек"))
        self.label_responseTimeout_1.setText(_translate("servers_settings", "Время ожидания ответа сервера"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    servers_settings = QtWidgets.QDialog()
    ui = Ui_servers_settings()
    ui.setupUi(servers_settings)
    servers_settings.show()
    sys.exit(app.exec_())
