# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_set_window_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_servers_settings(object):
    def setupUi(self, servers_settings):
        servers_settings.setObjectName("servers_settings")
        servers_settings.setWindowModality(QtCore.Qt.ApplicationModal)
        servers_settings.resize(379, 104)
        servers_settings.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(servers_settings)
        self.buttonBox.setGeometry(QtCore.QRect(30, 66, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_serverAddress = QtWidgets.QLabel(servers_settings)
        self.label_serverAddress.setGeometry(QtCore.QRect(13, 10, 111, 17))
        self.label_serverAddress.setObjectName("label_serverAddress")
        self.lineEdit_serverAddress = QtWidgets.QLineEdit(servers_settings)
        self.lineEdit_serverAddress.setGeometry(QtCore.QRect(10, 32, 361, 25))
        self.lineEdit_serverAddress.setClearButtonEnabled(True)
        self.lineEdit_serverAddress.setObjectName("lineEdit_serverAddress")

        self.retranslateUi(servers_settings)
        self.buttonBox.accepted.connect(servers_settings.accept) # type: ignore
        self.buttonBox.rejected.connect(servers_settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(servers_settings)

    def retranslateUi(self, servers_settings):
        _translate = QtCore.QCoreApplication.translate
        servers_settings.setWindowTitle(_translate("servers_settings", "Настройки подключения к серверу"))
        self.label_serverAddress.setText(_translate("servers_settings", "Адрес сервера:"))
        self.lineEdit_serverAddress.setText(_translate("servers_settings", "http://127.0.0.1:8000/api/v1/start/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    servers_settings = QtWidgets.QDialog()
    ui = Ui_servers_settings()
    ui.setupUi(servers_settings)
    servers_settings.show()
    sys.exit(app.exec_())
